#! /bin/sh

sxhkd &
polybar example & 

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off