require('plugins.compe');
require('plugins.maximizer');
require('plugins.neoformat');
require('plugins.nvimTree');
require('plugins.telescope');
-- require('plugins.treesitter');
require('plugins.undotree');
require('plugins.vimspector');
require('plugins.vimtest');
require('plugins.whichkey');
